# Generated by Django 4.1.3 on 2022-12-16 13:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('admission_portal', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Admission_users',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('admission_username', models.CharField(max_length=200)),
                ('admission_password', models.CharField(max_length=50)),
            ],
        ),
    ]
