# Generated by Django 4.1.3 on 2022-12-16 15:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('admission_portal', '0002_admission_users'),
    ]

    operations = [
        migrations.CreateModel(
            name='Application_information',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('entry_term', models.CharField(choices=[('2023 SPRING', '2023 Spring'), ('2023 WINTER', '2023 Winter'), ('2023 FALL', '2023 Fall')], max_length=50)),
            ],
        ),
    ]
