# Generated by Django 4.1.3 on 2022-12-16 20:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('admission_portal', '0003_application_information'),
    ]

    operations = [
        migrations.CreateModel(
            name='Personal_info',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Give_name', models.CharField(max_length=100)),
                ('Middle_name', models.CharField(max_length=100)),
                ('Family_name', models.CharField(max_length=100)),
                ('Preffered_first_name', models.CharField(max_length=100)),
                ('Preffered_family_name', models.CharField(max_length=100)),
                ('Address', models.CharField(max_length=100)),
                ('City', models.CharField(max_length=100)),
                ('Phone', models.CharField(max_length=100)),
                ('Email', models.CharField(max_length=100)),
            ],
        ),
        migrations.DeleteModel(
            name='Application_information',
        ),
    ]
