# Generated by Django 4.1.3 on 2022-12-16 20:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('admission_portal', '0004_personal_info_delete_application_information'),
    ]

    operations = [
        migrations.RenameField(
            model_name='personal_info',
            old_name='Give_name',
            new_name='Given_name',
        ),
    ]
