# Generated by Django 4.1.3 on 2022-12-16 21:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('admission_portal', '0006_demographics_info_alter_personal_info_options'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Demographics_info',
        ),
        migrations.AddField(
            model_name='personal_info',
            name='Birthday',
            field=models.DateField(null=True),
        ),
        migrations.AddField(
            model_name='personal_info',
            name='Country_of_residence',
            field=models.CharField(max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='personal_info',
            name='First_language',
            field=models.CharField(max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='personal_info',
            name='Gender',
            field=models.CharField(max_length=50, null=True),
        ),
    ]
