# Generated by Django 4.1.3 on 2022-12-16 21:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('admission_portal', '0008_personal_info_kin_address_personal_info_kin_city_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='personal_info',
            name='Declaration_authorization',
            field=models.CharField(choices=[('YES', 'Yes'), ('NO', 'No')], max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='personal_info',
            name='School_city',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='personal_info',
            name='School_name',
            field=models.CharField(max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='personal_info',
            name='Signature',
            field=models.CharField(max_length=300, null=True),
        ),
    ]
