# Generated by Django 4.1.3 on 2022-12-16 21:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('admission_portal', '0009_personal_info_declaration_authorization_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='personal_info',
            name='Signature_date',
            field=models.DateField(auto_now_add=True, null=True),
        ),
    ]
