# Generated by Django 4.1.3 on 2022-12-16 21:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('admission_portal', '0010_personal_info_signature_date'),
    ]

    operations = [
        migrations.AddField(
            model_name='personal_info',
            name='Academic_program',
            field=models.CharField(max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='personal_info',
            name='Admission_category',
            field=models.CharField(max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='personal_info',
            name='Agreement',
            field=models.CharField(choices=[('YES', 'Yes'), ('NO', 'No')], max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='personal_info',
            name='Area_of_interest',
            field=models.CharField(max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='personal_info',
            name='Campus',
            field=models.CharField(max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='personal_info',
            name='Entry_term',
            field=models.CharField(max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='personal_info',
            name='Student_id',
            field=models.CharField(max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='personal_info',
            name='Student_type',
            field=models.CharField(max_length=200, null=True),
        ),
    ]
