# Generated by Django 4.1.3 on 2022-12-20 08:59

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('admission_portal', '0012_course_listing_alter_personal_info_signature_date'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Profile',
        ),
        migrations.RemoveField(
            model_name='admission_users',
            name='admission_password',
        ),
        migrations.RemoveField(
            model_name='admission_users',
            name='admission_username',
        ),
        migrations.AddField(
            model_name='admission_users',
            name='department',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='admission_users',
            name='user',
            field=models.OneToOneField(null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
    ]
