# Generated by Django 4.1.3 on 2022-12-28 10:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('admission_portal', '0013_delete_profile_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Staff_information',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
            ],
        ),
    ]
